/** Tokens lifted from the design canvas (design/routefinder-screens.html). */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#006c49',
        'on-primary': '#ffffff',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        secondary: '#4b41e1',
        'on-secondary': '#ffffff',
        'secondary-container': '#645efb',
        'secondary-fixed': '#e2dfff',
        'on-secondary-fixed': '#0f0069',
        'on-secondary-fixed-variant': '#3323cc',
        tertiary: '#855300',
        'tertiary-container': '#e29100',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-container': '#523200',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#faf8ff',
        'surface-lowest': '#ffffff',
        'surface-low': '#f2f3ff',
        'surface-c': '#eaedff',
        'surface-high': '#e2e7ff',
        'surface-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#3c4a42',
        outline: '#6c7a71',
        'outline-variant': '#bbcabf',
        'success-container': '#d8f3e5',
        map: '#eaefe9',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        float: '0 6px 20px rgba(19,27,46,0.16)',
        chip: '0 3px 12px rgba(19,27,46,0.13)',
        sheet: '0 -6px 24px rgba(19,27,46,0.16)',
      },
    },
  },
  plugins: [],
};
